services:
  proxy:
    image: ghcr.io/e8035669/sekai-proxy:main
    build: .
    command: ["supervisord", "-c", "supervisord.conf"]
    volumes:
      - ./data/mitmproxy:/app/data/mitmproxy
    ports:
      - 8080:8080
      - 127.0.0.1:8081:8081
      - 127.0.0.1:8082:8082
      - 51820:51820/udp
      - 51820:51820

