[workspace]
authors = ["Yu-Ren Zhang <e8035669@gmail.com>"]
channels = ["conda-forge"]
name = "temp1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
dump = "mitmdump -s addon.py"
web = "mitmweb -s addon.py"
webui = "python webapp.py"

[dependencies]
python = "3.13.*"
pyperclip = ">=1.9.0,<2"

[pypi-dependencies]
sssekai = ">=0.7.44, <0.8"
mitmproxy = ">12"
nicegui = ">=2.22.1, <3"
