[workspace]
authors = ["Yu-Ren Zhang <e8035669@gmail.com>"]
channels = ["conda-forge"]
name = "temp1"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
dump = "mitmdump -s addon.py"
web1 = "mitmweb -s addon.py --mode wireguard --set confdir=data/mitmproxy --set listen_port=51820 --set web_host=0.0.0.0 --set web_port=8081 --set web_password=123456"
web2 = "mitmweb -s addon.py --mode regular --set confdir=data/mitmproxy --set listen_port=51820 --set web_host=0.0.0.0 --set web_port=8082 --set web_password=123456 --proxyauth=123456:123456"
webui = "python webapp.py"

# command: ["mitmweb", "-s", "/app/addon.py", "--mode", "wireguard", "--mode", "regular", "--set", "listen_port=51820", "--set", "web_host=0.0.0.0", "--set", "web_password=123456"]

[dependencies]
python = "3.13.*"
pyperclip = ">=1.9.0,<2"
supervisor = ">=4.2.5,<5"

[pypi-dependencies]
sssekai = ">=0.7.44, <0.8"
mitmproxy = ">12"
nicegui = ">=2.22.1, <3"
